# Generated by Django 4.0.5 on 2022-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_seller_location_seller_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
