# Generated by Django 4.0.5 on 2022-07-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=200, verbose_name='Gamintojas')),
                ('car_model', models.CharField(max_length=200, verbose_name='Modelis')),
                ('car_year', models.DateField(verbose_name='Gamybos metai')),
                ('car_engine', models.CharField(max_length=200, verbose_name='Variklis')),
                ('car_millage', models.IntegerField(verbose_name='Automobilio rida')),
                ('car_fuel_type', models.CharField(max_length=20, verbose_name='Kūro tipas')),
                ('car_chassis_type', models.CharField(max_length=100, verbose_name='Kebulo tipas')),
                ('car_door_number', models.CharField(max_length=10, null=True, verbose_name='Durų skaičius')),
                ('car_drive_wheel', models.CharField(max_length=30, null=True, verbose_name='Varantieji ratai')),
                ('car_transmission', models.CharField(max_length=50, verbose_name='Pavarų dėžė')),
                ('car_color', models.CharField(max_length=100, verbose_name='Spalva')),
                ('car_MOT', models.DateField(verbose_name='Tech. apžiūra iki')),
                ('car_weight', models.IntegerField(verbose_name='Automobilio masė')),
                ('car_vin_number', models.CharField(max_length=30, verbose_name='Automobilio numeris (VIN)')),
                ('car_poster_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
