# Generated by Django 4.0.5 on 2022-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_carposter_options_carposter_poster_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carposter',
            name='car_poster_price',
            field=models.IntegerField(default=None, verbose_name='Skelbimo suma'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='poster_sold_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Skelbimo pardavimo data'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Patvirtintas'), ('w', 'Laukiamas'), ('r', 'Atmestas'), ('s', 'Parduota/Neaktyvus')], default='w', help_text='Statusas', max_length=1),
        ),
    ]
