# Generated by Django 4.0.5 on 2022-08-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_carposter_car_poster_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carposter',
            options={'ordering': ['poster_date'], 'verbose_name': 'Skelbimas', 'verbose_name_plural': 'Skelbimai'},
        ),
    ]
