# Generated by Django 4.0.5 on 2022-08-08 15:56

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_alter_carposter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carposter',
            name='car_photo_1',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 1'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_10',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 10'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_2',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 2'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_3',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 3'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_4',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 4'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_5',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 5'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_6',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 6'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_7',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 7'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_8',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 8'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='car_photo_9',
            field=models.ImageField(default='no_car_photo.png', null=True, upload_to='poster-photos', verbose_name='Skelbimo nuotrauka 9'),
        ),
        migrations.AddField(
            model_name='carposter',
            name='description',
            field=tinymce.models.HTMLField(default='For more info Call'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_MOT',
            field=models.DateField(help_text='Automobilio techninės apžiūros pabaigos data', verbose_name='Tech. apžiūra iki'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_chassis_type',
            field=models.CharField(help_text='Automobilio kebulo tipas/forma', max_length=100, verbose_name='Kebulo tipas'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_color',
            field=models.CharField(help_text='Automobilio kebulo spalva', max_length=100, verbose_name='Spalva'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_door_number',
            field=models.CharField(help_text='Automobilio dūrų skaičius', max_length=10, null=True, verbose_name='Durų skaičius'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_drive_wheel',
            field=models.CharField(help_text='Automobilio varantieji ratai', max_length=30, null=True, verbose_name='Varantieji ratai'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_engine',
            field=models.CharField(help_text='Automobilio darbinis tūris ir sutrumpintas variklio pavadinimas', max_length=200, verbose_name='Variklis'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_fuel_type',
            field=models.CharField(help_text='Automobilio variklio kūro tipas', max_length=20, verbose_name='Kūro tipas'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_make',
            field=models.CharField(help_text='Automobilio gamintojo pavadinimas', max_length=200, verbose_name='Gamintojas'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_millage',
            field=models.IntegerField(help_text='Automobilio nuvažiotas kilometražas (KM)', verbose_name='Automobilio rida'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_model',
            field=models.CharField(help_text='Automobilio gamintojo modelis', max_length=200, verbose_name='Modelis'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_poster_price',
            field=models.IntegerField(default=None, help_text='Parduodamo automobilio kaina', verbose_name='Skelbimo suma'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_transmission',
            field=models.CharField(help_text='Automobilio pavarų dežės tipas', max_length=50, verbose_name='Pavarų dėžė'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_vin_number',
            field=models.CharField(help_text='Automobilio kebulo numeris/indentifikavimo numeris', max_length=30, verbose_name='Automobilio numeris (VIN)'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_weight',
            field=models.IntegerField(help_text='Automobilio nuosava masė', verbose_name='Automobilio masė'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='car_year',
            field=models.DateField(help_text='Automobilio pagaminimo metai', verbose_name='Gamybos metai'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='poster_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Skelbimo sukurimo data', verbose_name='Skelbimo data'),
        ),
    ]
