# Generated by Django 4.0.5 on 2022-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_carposter_car_photo_1_carposter_car_photo_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carposter',
            name='poster_sold_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Skelbimo pardavimo data'),
        ),
    ]
