# Generated by Django 4.0.5 on 2022-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_alter_carposter_poster_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carposter',
            name='car_poster_price',
            field=models.IntegerField(help_text='Parduodamo automobilio kaina', verbose_name='Skelbimo suma'),
        ),
        migrations.AlterField(
            model_name='carposter',
            name='poster_sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Skelbimo pardavimo data'),
        ),
    ]
