# Generated by Django 4.0.5 on 2022-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0008_remove_carposter_poster_sold_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carposter',
            name='sold_date',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Skelbimo pardavimo data'),
        ),
    ]
