# Generated by Django 4.0.5 on 2022-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0009_carposter_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carposter',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Skelbimo pardavimo data'),
        ),
    ]
