# Generated by Django 4.0.5 on 2022-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_remove_carposter_sold_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carposter',
            name='read_count',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='carposter',
            name='sold_date',
            field=models.DateTimeField(blank=True, help_text='Skelbimo sukurimo data', null=True, verbose_name='Skelbimo pardavimo data'),
        ),
    ]
